// <auto-generated />
using System;
using AngularDotNet.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularDotNet.API.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20230314185616_createDB")]
    partial class createDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AngularDotNet.API.People", b =>
                {
                    b.Property<Guid>("idPeople")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("agePeople")
                        .HasColumnType("int");

                    b.Property<string>("lastNamePeople")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("namePeople")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("professionPeople")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPeople");

                    b.ToTable("Peoples");
                });
#pragma warning restore 612, 618
        }
    }
}
